services:
  db:
    image: postgres:13.2
    ports:
      - "5555:5432"
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 1s
      retries: 20
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    
  redis:
    image: redis:6.2.4
    ports:
      - "6385:6379"

  rabbitmq:
    image: rabbitmq:3.13.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
  
  # web:
  #   build: .
  #   command: script/startapp.sh
  #   volumes:
  #     - "./:/code"
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - config/.env