"""Initial tables

Revision ID: 3f834992c6c3
Revises: 
Create Date: 2024-10-12 17:29:19.026925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f834992c6c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('registered', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user')),
    schema='public'
    )
    op.create_index(op.f('ix_public_user_user_id'), 'user', ['user_id'], unique=False, schema='public')
    op.create_table('recipe',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipe_title', sa.String(), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('dislikes', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.CheckConstraint('dislikes >= 0', name=op.f('ck_recipe_dislikes_non_negative')),
    sa.CheckConstraint('length(recipe_title) < 1000', name=op.f('ck_recipe_recipe_title_length')),
    sa.CheckConstraint('likes >= 0', name=op.f('ck_recipe_likes_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['public.user.user_id'], name=op.f('fk_recipe_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe')),
    schema='public'
    )
    op.create_index(op.f('ix_public_recipe_id'), 'recipe', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_recipe_id'), table_name='recipe', schema='public')
    op.drop_table('recipe', schema='public')
    op.drop_index(op.f('ix_public_user_user_id'), table_name='user', schema='public')
    op.drop_table('user', schema='public')
    # ### end Alembic commands ###
